export const images = {
    shoes1: require('./shoes1.png'),
    shoes2: require('./shoes2.png'),
    shoes3: require('./shoes3.png'),
    shoes4: require('./shoes4.png'),
    shoes5: require('./shoes5.png'),
    shoes6: require('./shoes6.png'),
    logo: require('./white.png'),
    backgroundImage: require('./background.png'),
    notification: require('./Notification.png'),
    menu: require('./menu.png'),
    back: require('./back.png'),
    glass: require('./glass.png'),
    box: require('./box.png'),
}